### ISSUE TITLE
clientSecret retrieval

### ISSUE THREAD

**Issue by paranoid-android** [sandrinodimattia/node-armclient#1]
Where does one get the `clientSecret` or `servicePrincipalPassword` to use with the Arm Client? I am the administrator for my Azure Instance. Yet, no matter what I enter get a 401 error. This leads me to believe that I've put in an invalid clientSecret or servicePrincipalPassword. Yet, I'm not sure where to find those in the Azure Portal.

**Comment by sandrinodm** [comment]
This blog post explains how you can get the credentials: http://fabriccontroller.net/using-adal-and-the-azure-resource-manager-rest-api-from-within-a-webtask/
